/*
 * hw.h
 *
 *  Created on: 03 june 2022
 *      Author: Alex
 *
 *  2022 DEC 23
 *      added temperature parameters to the HW::init() allowing to initialize the hardware at the startup
 */

#ifndef HW_H_
#define HW_H_

/*
 * This is a fusion file to join c++ project and main.c file generated by CubeMX
 */

#include "stat.h"
#include "iron.h"
#include "gun.h"
#include "encoder.h"
#include "display.h"
#include "config.h"
#include "buzzer.h"
#include "nls_cfg.h"

extern TIM_HandleTypeDef htim3;
extern TIM_HandleTypeDef htim4;

class HW {
	public:
		HW(void) : cfg(),
			u_enc(&htim3),
			l_enc(&htim4)									{ }
		uint16_t			ambientInternal(void)			{ return t_amb.read();							}
		bool				noAmbientSensor(void)			{ return t_amb.read() >= max_ambient_value;		}
		void				updateAmbient(uint16_t value)	{ t_amb.update(value);							}
		void				initAmbient(uint16_t value)		{ t_amb.reset(value);							}
		CFG_STATUS			init(uint16_t t12_temp, uint16_t jbc_temp, uint16_t gun_temp, uint16_t ambient);
		int32_t				ambientTemp(void);				// T12 IRON ambient temperature
		CFG			cfg;
		NLS			nls;
		DSPL		dspl;
		IRON		t12, jbc;
		RENC		u_enc, l_enc;							// Upper encoder and lower encoder
		HOTGUN		hotgun;
		BUZZER		buzz;
	private:
		EMP_AVERAGE 	t_amb;								// Exponential average of the ambient temperature
		const uint8_t	ambient_emp_coeff	= 30;			// Exponential average coefficient for ambient temperature
		const uint16_t	max_ambient_value	= 3900;			// About -30 degrees. If the soldering IRON disconnected completely, "ambient" value is greater than this
};

#endif
